In [1]:
# No terminal, uma vez: python -m pip install openpyxl pandas
import pandas as pd
import openpyxl

In [2]:
path = r"Tabela_3_Areas_gerais_de_formacao_na_graduacao.xlsx"

# Tabela 3 - Pessoas com nível superior completo, por áreas gerais de formação

A tabela possui 3 grandes grupos de áreas:
1. **Total** (todas as áreas / curso superior)
2. **Ciência, Tecnologia, Engenharias e Matemática** (STEM)
3. **Educação, Serviços pessoais, Saúde e Bem-estar**

In [1]:
# Lê o arquivo sem cabeçalho para visualizar a estrutura bruta
bruto = pd.read_excel(path, sheet_name="Sheet1", header=None)
bruto.head(15)

NameError: name 'pd' is not defined

In [4]:
# As linhas 3 a 35 contêm os dados (Brasil, regiões e UFs)
# As colunas são:
#   0: região
#   1 a 3: curso superior (Total, Homens, Mulheres)
#   4 a 6: STEM - Ciência, Tecnologia, Engenharias e Matemática
#   7 a 9: Educação, Serviços pessoais, Saúde e Bem-estar
dados = bruto.iloc[3:36].copy()
dados.reset_index(drop=True, inplace=True)
dados

,0,1,2,3,4,5,6,7,8,9
0,Brasil,25854291,10478534,15375757,4149041,2750422,1398619,8079707,1677985,6401723
1,Norte,1525166,590558,934609,209657,133055,76601,599785,141169,458616
2,Nordeste,4748933,1744994,3003939,621388,389993,231395,1822087,363905,1458181
3,Sudeste,12828829,5391638,7437191,2328122,1588874,739247,3652397,768288,2884108
4,Sul,4338861,1768855,2570005,662916,427372,235543,1256291,248574,1007718
5,Centro-Oeste,2412502,982489,1430013,326959,211124,115834,749148,156048,593101
6,Rondônia,164632,62766,101866,20538,11863,8675,63584,13963,49622
7,Acre,84300,33291,51009,10364,6237,4128,33379,9121,24258
8,Amazonas,342566,141059,201507,52669,34749,17919,121988,30738,91249
9,Roraima,67045,25585,41460,8016,4958,3057,23977,5880,18098
10,Pará,601096,229285,371811,86691,55481,31211,248397,58128,190270
11,Amapá,89191,35085,54106,11349,7464,3885,36754,9794,26960
12,Tocantins,176336,63485,112851,20028,12304,7724,71705,13548,58158
13,Maranhão,468681,161352,307329,55068,33820,21248,206222,40667,165555
14,Piauí,304955,108371,196584,37135,21668,15467,128416,25959,102457
15,Ceará,759303,285013,474290,99062,63935,35126,294578,64582,229996
16,Rio Grande do Norte,339913,131178,208735,46857,30398,16459,135434,28273,107161
17,Paraíba,390742,147221,243521,52223,33369,18855,150862,30025,120837
18,Pernambuco,852481,321587,530893,120260,73253,47007,281695,57333,224362
19,Alagoas,267996,98462,169534,33596,21398,12198,106971,20060,86911
20,Sergipe,218255,80608,137646,29020,17596,11422,83176,16801,66376
21,Bahia,1146608,411202,735406,148167,94556,53612,434735,80208,354528
22,Minas Gerais,2615434,1031532,1583902,452258,291778,160479,832482,157960,674521
23,Espírito Santo,491101,193756,297344,75667,49648,26018,161332,29788,131544
24,Rio de Janeiro,2243707,942645,1301062,406529,265723,140805,612263,145864,466399
25,São Paulo,7478587,3223705,4254883,1393668,981724,411944,2046321,434677,1611645
26,Paraná,1687930,695425,992505,255635,166579,89056,501471,98191,403280
27,Santa Catarina,1162515,489557,672958,185742,126554,59188,333537,67571,265964
28,Rio Grande do Sul,1488416,583873,904542,221541,134240,87300,421284,82812,338472
29,Mato Grosso do Sul,366249,145341,220908,46340,28241,18100,128352,26911,101443
30,Mato Grosso,450264,173267,276997,56776,33307,23468,141121,27052,114069
31,Goiás,879270,350828,528443,116867,74711,42156,288616,56564,232052
32,Distrito Federal,716719,313054,403665,106976,74866,32109,191061,45521,145538

In [5]:
# Nomeando as colunas com base na estrutura da tabela
dados.columns = [
    "regiao",
    "sup_total", "sup_homens", "sup_mulheres",
    "stem_total", "stem_homens", "stem_mulheres",
    "ed_total", "ed_homens", "ed_mulheres",
]
dados

,regiao,sup_total,sup_homens,sup_mulheres,stem_total,stem_homens,stem_mulheres,ed_total,ed_homens,ed_mulheres
0,Brasil,25854291,10478534,15375757,4149041,2750422,1398619,8079707,1677985,6401723
1,Norte,1525166,590558,934609,209657,133055,76601,599785,141169,458616
2,Nordeste,4748933,1744994,3003939,621388,389993,231395,1822087,363905,1458181
3,Sudeste,12828829,5391638,7437191,2328122,1588874,739247,3652397,768288,2884108
4,Sul,4338861,1768855,2570005,662916,427372,235543,1256291,248574,1007718
5,Centro-Oeste,2412502,982489,1430013,326959,211124,115834,749148,156048,593101
6,Rondônia,164632,62766,101866,20538,11863,8675,63584,13963,49622
7,Acre,84300,33291,51009,10364,6237,4128,33379,9121,24258
8,Amazonas,342566,141059,201507,52669,34749,17919,121988,30738,91249
9,Roraima,67045,25585,41460,8016,4958,3057,23977,5880,18098
10,Pará,601096,229285,371811,86691,55481,31211,248397,58128,190270
11,Amapá,89191,35085,54106,11349,7464,3885,36754,9794,26960
12,Tocantins,176336,63485,112851,20028,12304,7724,71705,13548,58158
13,Maranhão,468681,161352,307329,55068,33820,21248,206222,40667,165555
14,Piauí,304955,108371,196584,37135,21668,15467,128416,25959,102457
15,Ceará,759303,285013,474290,99062,63935,35126,294578,64582,229996
16,Rio Grande do Norte,339913,131178,208735,46857,30398,16459,135434,28273,107161
17,Paraíba,390742,147221,243521,52223,33369,18855,150862,30025,120837
18,Pernambuco,852481,321587,530893,120260,73253,47007,281695,57333,224362
19,Alagoas,267996,98462,169534,33596,21398,12198,106971,20060,86911
20,Sergipe,218255,80608,137646,29020,17596,11422,83176,16801,66376
21,Bahia,1146608,411202,735406,148167,94556,53612,434735,80208,354528
22,Minas Gerais,2615434,1031532,1583902,452258,291778,160479,832482,157960,674521
23,Espírito Santo,491101,193756,297344,75667,49648,26018,161332,29788,131544
24,Rio de Janeiro,2243707,942645,1301062,406529,265723,140805,612263,145864,466399
25,São Paulo,7478587,3223705,4254883,1393668,981724,411944,2046321,434677,1611645
26,Paraná,1687930,695425,992505,255635,166579,89056,501471,98191,403280
27,Santa Catarina,1162515,489557,672958,185742,126554,59188,333537,67571,265964
28,Rio Grande do Sul,1488416,583873,904542,221541,134240,87300,421284,82812,338472
29,Mato Grosso do Sul,366249,145341,220908,46340,28241,18100,128352,26911,101443
30,Mato Grosso,450264,173267,276997,56776,33307,23468,141121,27052,114069
31,Goiás,879270,350828,528443,116867,74711,42156,288616,56564,232052
32,Distrito Federal,716719,313054,403665,106976,74866,32109,191061,45521,145538

In [6]:
# Convertendo as colunas numéricas
for col in dados.columns[1:]:
    dados[col] = pd.to_numeric(dados[col], errors="coerce")
dados

,regiao,sup_total,sup_homens,sup_mulheres,stem_total,stem_homens,stem_mulheres,ed_total,ed_homens,ed_mulheres
0,Brasil,25854291,10478534,15375757,4149041,2750422,1398619,8079707,1677985,6401723
1,Norte,1525166,590558,934609,209657,133055,76601,599785,141169,458616
2,Nordeste,4748933,1744994,3003939,621388,389993,231395,1822087,363905,1458181
3,Sudeste,12828829,5391638,7437191,2328122,1588874,739247,3652397,768288,2884108
4,Sul,4338861,1768855,2570005,662916,427372,235543,1256291,248574,1007718
5,Centro-Oeste,2412502,982489,1430013,326959,211124,115834,749148,156048,593101
6,Rondônia,164632,62766,101866,20538,11863,8675,63584,13963,49622
7,Acre,84300,33291,51009,10364,6237,4128,33379,9121,24258
8,Amazonas,342566,141059,201507,52669,34749,17919,121988,30738,91249
9,Roraima,67045,25585,41460,8016,4958,3057,23977,5880,18098
10,Pará,601096,229285,371811,86691,55481,31211,248397,58128,190270
11,Amapá,89191,35085,54106,11349,7464,3885,36754,9794,26960
12,Tocantins,176336,63485,112851,20028,12304,7724,71705,13548,58158
13,Maranhão,468681,161352,307329,55068,33820,21248,206222,40667,165555
14,Piauí,304955,108371,196584,37135,21668,15467,128416,25959,102457
15,Ceará,759303,285013,474290,99062,63935,35126,294578,64582,229996
16,Rio Grande do Norte,339913,131178,208735,46857,30398,16459,135434,28273,107161
17,Paraíba,390742,147221,243521,52223,33369,18855,150862,30025,120837
18,Pernambuco,852481,321587,530893,120260,73253,47007,281695,57333,224362
19,Alagoas,267996,98462,169534,33596,21398,12198,106971,20060,86911
20,Sergipe,218255,80608,137646,29020,17596,11422,83176,16801,66376
21,Bahia,1146608,411202,735406,148167,94556,53612,434735,80208,354528
22,Minas Gerais,2615434,1031532,1583902,452258,291778,160479,832482,157960,674521
23,Espírito Santo,491101,193756,297344,75667,49648,26018,161332,29788,131544
24,Rio de Janeiro,2243707,942645,1301062,406529,265723,140805,612263,145864,466399
25,São Paulo,7478587,3223705,4254883,1393668,981724,411944,2046321,434677,1611645
26,Paraná,1687930,695425,992505,255635,166579,89056,501471,98191,403280
27,Santa Catarina,1162515,489557,672958,185742,126554,59188,333537,67571,265964
28,Rio Grande do Sul,1488416,583873,904542,221541,134240,87300,421284,82812,338472
29,Mato Grosso do Sul,366249,145341,220908,46340,28241,18100,128352,26911,101443
30,Mato Grosso,450264,173267,276997,56776,33307,23468,141121,27052,114069
31,Goiás,879270,350828,528443,116867,74711,42156,288616,56564,232052
32,Distrito Federal,716719,313054,403665,106976,74866,32109,191061,45521,145538

# Tabela 1 - Homens e mulheres por região com curso superior

In [7]:
superior = dados[["regiao", "sup_homens", "sup_mulheres"]].copy()
superior.columns = ["regiao", "homens", "mulheres"]
superior

                 regiao    homens  mulheres
0                Brasil  10478534  15375757
1                 Norte    590558    934609
2              Nordeste   1744994   3003939
3               Sudeste   5391638   7437191
4                   Sul   1768855   2570005
5          Centro-Oeste    982489   1430013
6              Rondônia     62766    101866
7                  Acre     33291     51009
8              Amazonas    141059    201507
9               Roraima     25585     41460
10                 Pará    229285    371811
11                Amapá     35085     54106
12            Tocantins     63485    112851
13             Maranhão    161352    307329
14                Piauí    108371    196584
15                Ceará    285013    474290
16  Rio Grande do Norte    131178    208735
17              Paraíba    147221    243521
18           Pernambuco    321587    530893
19              Alagoas     98462    169534
20              Sergipe     80608    137646
21                Bahia    411202    735406
22         Minas Gerais   1031532   1583902
23       Espírito Santo    193756    297344
24       Rio de Janeiro    942645   1301062
25            São Paulo   3223705   4254883
26               Paraná    695425    992505
27       Santa Catarina    489557    672958
28    Rio Grande do Sul    583873    904542
29   Mato Grosso do Sul    145341    220908
30          Mato Grosso    173267    276997
31                Goiás    350828    528443
32     Distrito Federal    313054    403665

In [8]:
superior.describe().round(2)

            homens     mulheres
count        33.00        33.00
mean     952593.97   1397796.09
std     2020681.05   2918446.17
min       25585.00     41460.00
25%      131178.00    201507.00
50%      285013.00    403665.00
75%      695425.00    992505.00
max    10478534.00  15375757.00

# Tabela 2 - Homens e mulheres por região com curso nas áreas de Ciência, Tecnologia, Engenharias e Matemática (STEM)

In [9]:
stem = dados[["regiao", "stem_homens", "stem_mulheres"]].copy()
stem.columns = ["regiao", "homens", "mulheres"]
stem

                 regiao   homens  mulheres
0                Brasil  2750422   1398619
1                 Norte   133055     76601
2              Nordeste   389993    231395
3               Sudeste  1588874    739247
4                   Sul   427372    235543
5          Centro-Oeste   211124    115834
6              Rondônia    11863      8675
7                  Acre     6237      4128
8              Amazonas    34749     17919
9               Roraima     4958      3057
10                 Pará    55481     31211
11                Amapá     7464      3885
12            Tocantins    12304      7724
13             Maranhão    33820     21248
14                Piauí    21668     15467
15                Ceará    63935     35126
16  Rio Grande do Norte    30398     16459
17              Paraíba    33369     18855
18           Pernambuco    73253     47007
19              Alagoas    21398     12198
20              Sergipe    17596     11422
21                Bahia    94556     53612
22         Minas Gerais   291778    160479
23       Espírito Santo    49648     26018
24       Rio de Janeiro   265723    140805
25            São Paulo   981724    411944
26               Paraná   166579     89056
27       Santa Catarina   126554     59188
28    Rio Grande do Sul   134240     87300
29   Mato Grosso do Sul    28241     18100
30          Mato Grosso    33307     23468
31                Goiás    74711     42156
32     Distrito Federal    74866     32109

In [10]:
stem.describe().round(2)

           homens    mulheres
count       33.00       33.00
mean    250038.18   127147.12
std     549079.01   270735.21
min       4958.00     3057.00
25%      28241.00    16459.00
50%      63935.00    32109.00
75%     166579.00    89056.00
max    2750422.00  1398619.00

# Tabela 3 - Homens e mulheres por região com curso nas áreas de Educação, Serviços pessoais, Saúde e Bem-estar

In [11]:
educacao = dados[["regiao", "ed_homens", "ed_mulheres"]].copy()
educacao.columns = ["regiao", "homens", "mulheres"]
educacao

                 regiao   homens  mulheres
0                Brasil  1677985   6401723
1                 Norte   141169    458616
2              Nordeste   363905   1458181
3               Sudeste   768288   2884108
4                   Sul   248574   1007718
5          Centro-Oeste   156048    593101
6              Rondônia    13963     49622
7                  Acre     9121     24258
8              Amazonas    30738     91249
9               Roraima     5880     18098
10                 Pará    58128    190270
11                Amapá     9794     26960
12            Tocantins    13548     58158
13             Maranhão    40667    165555
14                Piauí    25959    102457
15                Ceará    64582    229996
16  Rio Grande do Norte    28273    107161
17              Paraíba    30025    120837
18           Pernambuco    57333    224362
19              Alagoas    20060     86911
20              Sergipe    16801     66376
21                Bahia    80208    354528
22         Minas Gerais   157960    674521
23       Espírito Santo    29788    131544
24       Rio de Janeiro   145864    466399
25            São Paulo   434677   1611645
26               Paraná    98191    403280
27       Santa Catarina    67571    265964
28    Rio Grande do Sul    82812    338472
29   Mato Grosso do Sul    26911    101443
30          Mato Grosso    27052    114069
31                Goiás    56564    232052
32     Distrito Federal    45521    145538

In [12]:
educacao.describe().round(2)

           homens    mulheres
count       33.00       33.00
mean    152544.24   581974.91
std     314437.31  1197881.76
min       5880.00    18098.00
25%      26911.00   101443.00
50%      56564.00   190270.00
75%     141169.00   458616.00
max    1677985.00  6401723.00